/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mcam.UI;

import javax.swing.JButton;
import mcam.Core.CManager;
import mcam.Core.MPlayer;

/**
 *
 * @author Nived
 */
public class MUI extends javax.swing.JFrame {

    /**
     * Creates new form MCam
     */
    
    CManager mgr ;
    
    public MUI() {
        initComponents();
    }
    
    
    public void setManager(CManager mc)
    {
        this.mgr = mc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        previewPane = new javax.swing.JPanel();
        previewCamTitle = new javax.swing.JLabel();
        previewPanel = new javax.swing.JPanel();
        consoleLogPane = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        consoleTextArea = new javax.swing.JTextArea();
        camListPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        UIpreviewList = new javax.swing.JList<>();
        serviceControlPane = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        UIRecordingToggle = new javax.swing.JButton();
        UIpauseRecording = new javax.swing.JButton();
        UIStreamingToggle = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        previewPane.setBackground(new java.awt.Color(255, 255, 255));

        previewCamTitle.setBackground(new java.awt.Color(226, 226, 226));
        previewCamTitle.setText("Lenovo Cam ID:0");
        previewCamTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        previewCamTitle.setOpaque(true);

        previewPanel.setOpaque(false);

        javax.swing.GroupLayout previewPanelLayout = new javax.swing.GroupLayout(previewPanel);
        previewPanel.setLayout(previewPanelLayout);
        previewPanelLayout.setHorizontalGroup(
            previewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        previewPanelLayout.setVerticalGroup(
            previewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout previewPaneLayout = new javax.swing.GroupLayout(previewPane);
        previewPane.setLayout(previewPaneLayout);
        previewPaneLayout.setHorizontalGroup(
            previewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(previewCamTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)
            .addGroup(previewPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(previewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        previewPaneLayout.setVerticalGroup(
            previewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(previewPaneLayout.createSequentialGroup()
                .addComponent(previewCamTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(previewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(previewPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 9, 990, 500));

        consoleLogPane.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(226, 226, 226));
        jLabel2.setText("Console Log");
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        jLabel2.setOpaque(true);

        consoleTextArea.setEditable(false);
        consoleTextArea.setColumns(20);
        consoleTextArea.setRows(5);
        consoleTextArea.setWrapStyleWord(true);
        consoleTextArea.setBorder(null);
        jScrollPane1.setViewportView(consoleTextArea);

        javax.swing.GroupLayout consoleLogPaneLayout = new javax.swing.GroupLayout(consoleLogPane);
        consoleLogPane.setLayout(consoleLogPaneLayout);
        consoleLogPaneLayout.setHorizontalGroup(
            consoleLogPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consoleLogPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 966, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        consoleLogPaneLayout.setVerticalGroup(
            consoleLogPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consoleLogPaneLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(consoleLogPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 517, 990, 160));

        camListPane.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(226, 226, 226));
        jLabel1.setText("Webcam List");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jScrollPane2.setViewportView(UIpreviewList);

        javax.swing.GroupLayout camListPaneLayout = new javax.swing.GroupLayout(camListPane);
        camListPane.setLayout(camListPaneLayout);
        camListPaneLayout.setHorizontalGroup(
            camListPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
            .addGroup(camListPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        camListPaneLayout.setVerticalGroup(
            camListPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(camListPaneLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(camListPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(1009, 10, 280, 500));

        serviceControlPane.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(226, 226, 226));
        jLabel3.setText("Service Controls");
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        jLabel3.setOpaque(true);

        UIRecordingToggle.setText("Start Recording");
        UIRecordingToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UIRecordingToggleActionPerformed(evt);
            }
        });

        UIpauseRecording.setText("Pause Recording");
        UIpauseRecording.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UIpauseRecordingActionPerformed(evt);
            }
        });

        UIStreamingToggle.setText("Start Streaming");
        UIStreamingToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UIStreamingToggleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout serviceControlPaneLayout = new javax.swing.GroupLayout(serviceControlPane);
        serviceControlPane.setLayout(serviceControlPaneLayout);
        serviceControlPaneLayout.setHorizontalGroup(
            serviceControlPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
            .addGroup(serviceControlPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(serviceControlPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UIRecordingToggle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UIpauseRecording, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UIStreamingToggle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        serviceControlPaneLayout.setVerticalGroup(
            serviceControlPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(serviceControlPaneLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UIRecordingToggle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UIpauseRecording)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UIStreamingToggle)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        getContentPane().add(serviceControlPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(1009, 517, 280, 160));

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        jMenu1.setText("MCam");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Record");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Stream");
        jMenuBar1.add(jMenu3);

        jMenu5.setText("Playback");

        jMenuItem1.setText("Show Player");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuBar1.add(jMenu5);

        jMenu4.setText("Exit");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       MPlayer player = new MPlayer();
       player.init();
       player.Show();
       player.useDate("30-07-2017");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void UIRecordingToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UIRecordingToggleActionPerformed
        mgr.recButtonToggle((javax.swing.JButton)evt.getSource());
    }//GEN-LAST:event_UIRecordingToggleActionPerformed

    private void UIpauseRecordingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UIpauseRecordingActionPerformed
        mgr.pauseButtonToggle((javax.swing.JButton)evt.getSource());
    }//GEN-LAST:event_UIpauseRecordingActionPerformed

    private void UIStreamingToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UIStreamingToggleActionPerformed
        mgr.streamButtonToggle((javax.swing.JButton)evt.getSource());
    }//GEN-LAST:event_UIStreamingToggleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton UIRecordingToggle;
    public javax.swing.JButton UIStreamingToggle;
    public javax.swing.JButton UIpauseRecording;
    public javax.swing.JList<String> UIpreviewList;
    private javax.swing.JPanel camListPane;
    private javax.swing.JPanel consoleLogPane;
    public javax.swing.JTextArea consoleTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel previewCamTitle;
    public javax.swing.JPanel previewPane;
    public javax.swing.JPanel previewPanel;
    private javax.swing.JPanel serviceControlPane;
    // End of variables declaration//GEN-END:variables
}
